// packages/next/src/components/StructuredData/index.tsx
import type { StructuredDataWebSite } from '@epoxide/web-types'

interface StructuredDataProps {
  schema: StructuredDataWebSite
}

export function StructuredData({ schema }: StructuredDataProps) {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{
        __html: JSON.stringify({ ...schema, '@context': 'https://schema.org' }),
      }}
    />
  )
}

// packages/sveltekit/src/lib/components/StructuredData.svelte
<script lang="ts">
  import type { StructuredDataWebSite } from '@epoxide/web-types'

  export let schema: StructuredDataWebSite

  $: modifiedSchema = JSON.stringify({
    ...schema,
    '@context': 'https://schema.org',
  })
</script>

{@html "<script type=\"application/ld+json\">" + modifiedSchema + "</script>"}
