// packages/next/src/components/Footer/index.tsx
import type { StaticImageData } from 'next/image'
import Image from 'next/image'
import { FOOTER } from '@epoxide/web-constants'
import styles from './styles.module.scss'
import { IconButton } from '../IconButton'

interface FooterProps {
  src: string | StaticImageData
}

export function Footer({ src }: FooterProps) {
  return (
    <footer className={styles.footer}>
      <div className={styles.titleLogo}>
        <Image
          src={src}
          alt={FOOTER.LOGO.ALT}
          width={FOOTER.LOGO.SIZE}
          height={FOOTER.LOGO.SIZE}
        />
        <span>{FOOTER.TITLE}</span>
      </div>
      <section className={styles.socialMediaLinks}>
        {FOOTER.SOCIAL_MEDIA_LINKS.map((link) => {
          return (
            <IconButton
              href={link.URL}
              target="_blank"
              icon={link.ICON}
              key={link.ICON}
              iconLibrary="brands"
              size="xl"
              ariaLabel={link.ARIA_LABEL}
            />
          )
        })}
      </section>
    </footer>
  )
}

// packages/solid-start/src/components/Footer.tsx
import { For } from 'solid-js'
import { FOOTER } from '@epoxide/web-constants'
import './Footer.scss'
import IconButton from '~/components/IconButton'

interface FooterProps {
  src: string
}

export default function Footer(props: FooterProps) {
  return (
    <footer>
      <div class="title-logo">
        <img
          src={props.src}
          alt={FOOTER.LOGO.ALT}
          width={FOOTER.LOGO.SIZE}
          height={FOOTER.LOGO.SIZE}
        />
        <span>{FOOTER.TITLE}</span>
      </div>
      <section class="social-media-links">
        <For each={FOOTER.SOCIAL_MEDIA_LINKS}>
          {(link) => {
            return (
              <IconButton
                href={link.URL}
                target="_blank"
                icon={link.ICON}
                iconLibrary="brands"
                size="xl"
                ariaLabel={link.ARIA_LABEL}
              />
            )
          }}
        </For>
      </section>
    </footer>
  )
}
