// packages/sveltekit/src/lib/components/StructuredData.svelte
<script lang="ts">
  import type { StructuredDataWebSite } from '@epoxide/web-types'

  export let schema: StructuredDataWebSite

  $: modifiedSchema = JSON.stringify({
    ...schema,
    '@context': 'https://schema.org',
  })
</script>

{@html "<script type=\"application/ld+json\">" + modifiedSchema + "</script>"}

// packages/solid-start/src/components/StructuredData.tsx
import type { StructuredDataWebSite } from '@epoxide/web-types'

export interface StructuredDataProps {
  schema: StructuredDataWebSite
}

export default function StructuredData(props: StructuredDataProps) {
  return (
    <script type="application/ld+json">
      {JSON.stringify({ ...props.schema, '@context': 'https://schema.org' })}
    </script>
  )
}
