// packages/nuxt/app/components/StructuredData.vue
<script setup lang="ts">
import type { StructuredDataWebSite } from '@epoxide/web-types'

export interface Props {
  schema: StructuredDataWebSite
}

withDefaults(defineProps<Props>(), {})
</script>

<template>
  <component :is="'script'" type="application/ld+json">
    {{ JSON.stringify({ ...schema, '@context': 'https://schema.org' }) }}
  </component>
</template>

// packages/solid-start/src/components/StructuredData.tsx
import type { StructuredDataWebSite } from '@epoxide/web-types'

export interface StructuredDataProps {
  schema: StructuredDataWebSite
}

export default function StructuredData(props: StructuredDataProps) {
  return (
    <script type="application/ld+json">
      {JSON.stringify({ ...props.schema, '@context': 'https://schema.org' })}
    </script>
  )
}
